import java.io.*;
import java.util.ArrayList;
import java.util.List;

// Handles all video assembly using FFmpeg.
// Implements MediaOperation so it plugs cleanly into the pipeline in Main.
// The process has three stages:
//   1. Convert each media file into a normalized MP4 part
//   2. Concatenate all parts into one video with the narration audio
//   3. Convert the horizontal video to portrait mode with a blurred background
public class VideoCreator implements MediaOperation {

    private final String audioPath;   // path to the narration MP3 generated by ApiHandler
    private final String videoname;   // desired output filename (without .mp4)

    // Durations in seconds — change these to adjust the video timing
    private static final int IAImageDuration  = 5;  // AI cover image
    private static final int ImageDuration    = 5;  // each user photo
    private static final int MapDuration     = 5;  // closing map slide

    // param audioPath the narration audio file to attach to the video
    // param finalName the name for the final portrait video output (without .mp4)
    public VideoCreator(String audioPath, String videoname) {
        this.audioPath = audioPath;
        this.videoname = videoname;
    }

    // Entry point for the MediaOperation interface.
    // Assembles the full video from the sorted media array.
    // param media the sorted array of MediaFile objects (oldest to newest)
    // throws Exception if any FFmpeg command or file operation fails
    @Override
    public void execute(MediaFile[] media) throws Exception {
        List<File> parts = new ArrayList<>();

        //Opening the AiImage
        System.out.println("making video the opening AIImage");
        File AiImage = new File("AiImage.png");
        if (!AiImage.exists()) {
            System.out.println("AiImage.png not found or not created");
        }
        parts.add(createImagePart(AiImage, IAImageDuration, "videopart_000.mp4"));

        // User media files (already sorted oldest to newest)
        for (int i = 0; i < media.length; i++) {
            File source = new File(media[i].mediaPath);
            File part;

            if (SortMedia.forVideo(source.getAbsolutePath())) {
                System.out.println("making video " + (i + 1) + "/" + media.length );
                part = createVideoPart(source, "videopart_" + (i + 1) + ".mp4");
            } else {
                System.out.println("making video " + (i + 1) + "/" + media.length + "...");
                part = createImagePart(source, ImageDuration, "videopart_" + (i + 1) + ".mp4");
            }

            parts.add(part);
        }

        // closing map image
        System.out.println("making video the map image");
        File mapImage = new File("mapImage.png");
        if (!mapImage.exists()) {
            System.out.println("    mapImage.png failed");
        }
        parts.add(createImagePart(mapImage, MapDuration, "videopart_last.mp4"));

        // Write the FFmpeg concat list
        File listFile = buildConcatList(parts);
        System.out.println("  - Total parts created: " + parts.size());

        //Merge all video parts + audio into one horizontal video
        System.out.println(" Compiling the final video with the audio");
        compileFinalVideo(listFile);

        //Convert horizontal video to portrait mode
        System.out.println("  Converting to portrait mode ");
        convertToPortrait("final_video.mp4", videoname + ".mp4");
    }



    // PARTS CREATION

    // Creates a fixed-duration MP4 part from a still image.
    // Scales the image to fill 1920x1080 and crops any overflow to keep aspect ratio.
    // param imageFile: the source image
    // param durationSeconds: how long this part should appear in the video
    // param outputName: the filename for the resulting part
    // returns the output File
    // throws Exception if FFmpeg exits with a non-zero code
    private File createImagePart(File imageFile, int durationSeconds, String outputName) throws Exception {
        File output = new File(outputName);

        String[] command = {
                "ffmpeg", "-y",
                "-loop", "1",
                "-i",    imageFile.getAbsolutePath(),
                "-t",    String.valueOf(durationSeconds),
                "-filter_complex", "[0:v]scale=1920:1080:force_original_aspect_ratio=increase,crop=1920:1080,boxblur=20:10[bg];" +
                        "[0:v]scale=1920:1080:force_original_aspect_ratio=decrease[fg];" +
                        "[bg][fg]overlay=(W-w)/2:(H-h)/2,format=yuv420p",
                "-r",    "30",
                "-c:v",  "libx264",
                output.getAbsolutePath()
        };

        runCommand(command, "image part " + outputName);
        return output;
    }

    // Creates a normalized MP4 part from a user video file.
    // Strips the original audio (-an) since the narration track replaces it.
    // Scales and crops the video to fill 1920x1080 while preserving aspect ratio.
    // param videoFile: the source video
    // param outputName: the filename for the resulting part
    // returns the output File
    // throws Exception if FFmpeg exits with a non-zero code
    private File createVideoPart(File videoFile, String outputName) throws Exception {
        File output = new File(outputName);

        String[] command = {
                "ffmpeg", "-y",
                "-i",   videoFile.getAbsolutePath(),
                "-filter_complex", "[0:v]scale=1920:1080:force_original_aspect_ratio=increase,crop=1920:1080,boxblur=20:10[bg];" +
                "[0:v]scale=1920:1080:force_original_aspect_ratio=decrease[fg];" +
                "[bg][fg]overlay=(W-w)/2:(H-h)/2,format=yuv420p",
                "-r",   "30",
                "-c:v", "libx264",
                "-an",  // strip original audio because narration replaces it
                output.getAbsolutePath()
        };

        runCommand(command, "video part " + outputName);
        return output;
    }


    // CONCATENATION & AUDIO

    // Writes the FFmpeg concat demuxer list file referencing all part paths.
    // Each line must use forward slashes even on Windows, so we normalize separators.
    // param parts the ordered list of part files to include
    // returns the list File ready to pass to FFmpeg
    // throws IOException if the file cannot be written
    private File buildConcatList(List<File> parts) throws IOException {
        File listFile = new File("input.txt");
        BufferedWriter writer = new BufferedWriter(new FileWriter(listFile));

        for (File part : parts) {
            writer.write("file '" + part.getAbsolutePath().replace("\\", "/") + "'\n");
        }

        writer.close();
        return listFile;
    }

    // Merges all parts with the narration audio into a single horizontal MP4.
    // Delays the audio by 3 seconds so it starts after the opening AiImage finishes.
    // Normalizes audio to -14 LUFS
    // param listFile the concat list file created by buildConcatList()
    // throws Exception if FFmpeg fails
    private void compileFinalVideo(File listFile) throws Exception {
        String[] command = {
                "ffmpeg", "-y",
                "-f",        "concat",
                "-safe",     "0",
                "-i",        listFile.getAbsolutePath(),
                "-i",        new File(audioPath).getAbsolutePath(),
                "-c:v",      "libx264",
                "-c:a",      "aac",
                "-b:a",      "192k",                        // high quality audio bitrate
                "-af",       "loudnorm=I=-14:TP=-1:LRA=7",  // normalize to -14 LUFS standard
                "-pix_fmt",  "yuv420p",
                "final_video.mp4"
        };

        int exitCode = runCommand(command, "final video");

        if (exitCode == 0) {
            System.out.println("  - Horizontal video created: final_video.mp4");
            System.out.println("  - Audio normalized to -14 LUFS / -1 dBTP / 7 LRA");
        }
    }


    // PORTRAIT CONVERSION

    // Converts the horizontal video to 1080x1920 portrait format.
    // Uses a blurred version of the video itself as the background to fill black bars,
    // then overlays the properly scaled content on top — no black bars, no cropping.
    // param inputVideo: the horizontal MP4 to convert
    // param outputVideo: the final portrait MP4 filename
    public void convertToPortrait(String inputVideo, String outputVideo) throws Exception {
        String[] command = {
                "ffmpeg", "-y",
                "-i", new File(inputVideo).getAbsolutePath(),
                "-lavfi",
                // [bg]: scale up and blur the video to fill the portrait frame completely
                // [fg]: scale the video down so it fits within 1080x1920 without cropping
                // overlay: center [fg] on top of [bg] so nothing is cut off
                "[0:v]scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,boxblur=20:10[bg];" +
                "[0:v]scale=1080:1920:force_original_aspect_ratio=decrease[fg];" +
                "[bg][fg]overlay=(W-w)/2:(H-h)/2",
                "-c:a", "copy",
                new File(outputVideo).getAbsolutePath()
        };

        runCommand(command, "portrait conversion");
        System.out.println("  - Portrait video created: " + outputVideo);
    }

    // AUDIO VERIFICATION

    // Checks the final video's audio loudness levels and prints a summary.
    // Useful to confirm the normalization applied in compileFinalVideo() worked correctly.
    // param videoPath the path to the final video to analyze
    public void verifyAudioLevels(String videoPath) {
        System.out.println("\n[Verifying] Checking audio loudness levels...");

        try {
            String[] command = {
                    "ffmpeg",
                    "-i",  new File(videoPath).getAbsolutePath(),
                    "-af", "loudnorm=print_format=summary",
                    "-f",  "null",
                    "-"
            };

            ProcessBuilder pb = new ProcessBuilder(command);
            pb.redirectErrorStream(true); // merge stderr into stdout so we can read everything
            Process process = pb.start();

            BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
            String line;
            boolean foundData = false;

            while ((line = reader.readLine()) != null) {
                // Only print the loudness summary lines, it skips all other FFmpeg output
                if (line.contains("Input Integrated:")  ||
                    line.contains("Input True Peak:")   ||
                    line.contains("Input LRA:")         ||
                    line.contains("Output Integrated:") ||
                    line.contains("Output True Peak:")  ||
                    line.contains("Output LRA:")) {
                    System.out.println("  " + line.trim());
                    foundData = true;
                }
            }

            process.waitFor();

            if (foundData) {
                // Remind what values are within spec after printing the actual numbers
                System.out.println("\n  Target standards:");
                System.out.println("    Loudness  : -16 to -14 LUFS");
                System.out.println("    True Peak : -2  to -1  dBTP");
                System.out.println("    LRA       :  5  to  10 LU");
            }

        } catch (Exception e) {
            System.out.println("  Could not verify audio levels: " + e.getMessage());
        }
    }


    // COMMAND RUNNER

    // Runs an external command and waits for it to finish.
    // Inherits the current process's I/O so FFmpeg output appears in the console,
    // keeping the user informed of what FFmpeg is doing at each step.
    // param command: the command and its arguments as a String array
    // param label: a short description used in the error message if the command fails
    // returns the exit code (0 = success)
    // throws Exception if the process exits with a non-zero code
    private int runCommand(String[] command, String label) throws Exception {
        Process process = new ProcessBuilder(command)
                .inheritIO() // pipe FFmpeg's output straight to the console
                .start();

        int exitCode = process.waitFor();

        if (exitCode != 0) {
            throw new RuntimeException("FFmpeg failed while processing [" + label + "] with exit code " + exitCode);
        }

        return exitCode;
    }
}
